# Generated by Django 3.0.5 on 2020-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRGid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100)),
                ('trg_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
